var a = 2;
var b = 6;
var c = 10;
var d = 4;
var e = 16;
console.log(a + " + " + b + " = " + (a + b) + "\n");
console.log(c + " - " + a + " = " + (c - a) + "\n");
console.log(d + " x " + a + " = " + (d * a) + "\n");
console.log(e + " / " + a + " = " + e / a);
